//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaticResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StaticResources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thứ tự.
        /// </summary>
        public static string Category_DisplayOrder {
            get {
                return ResourceManager.GetString("Category_DisplayOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả SEO.
        /// </summary>
        public static string Category_MetaDescription {
            get {
                return ResourceManager.GetString("Category_MetaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ khoá.
        /// </summary>
        public static string Category_Metakeyword {
            get {
                return ResourceManager.GetString("Category_Metakeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias.
        /// </summary>
        public static string Category_MetaTitle {
            get {
                return ResourceManager.GetString("Category_MetaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên danh mục.
        /// </summary>
        public static string Category_Name {
            get {
                return ResourceManager.GetString("Category_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục cha.
        /// </summary>
        public static string Category_ParentId {
            get {
                return ResourceManager.GetString("Category_ParentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu nhập tên danh mục.
        /// </summary>
        public static string Category_RequiredName {
            get {
                return ResourceManager.GetString("Category_RequiredName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu đề seo.
        /// </summary>
        public static string Category_SeoTitle {
            get {
                return ResourceManager.GetString("Category_SeoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiển thị trang chủ.
        /// </summary>
        public static string Category_ShowOnHome {
            get {
                return ResourceManager.GetString("Category_ShowOnHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        public static string Category_Status {
            get {
                return ResourceManager.GetString("Category_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập lại mật khẩu không chính xác.
        /// </summary>
        public static string ComfirmPasswordIncorrect {
            get {
                return ResourceManager.GetString("ComfirmPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa thông tin không thành công.
        /// </summary>
        public static string DeleteFailed {
            get {
                return ResourceManager.GetString("DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email đã tồn tại.
        /// </summary>
        public static string EmailExists {
            get {
                return ResourceManager.GetString("EmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếng Anh.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới vị trí quảng cáo không thành công.
        /// </summary>
        public static string InsertAdsPostitionFailed {
            get {
                return ResourceManager.GetString("InsertAdsPostitionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới quảng cáo không thành công.
        /// </summary>
        public static string InsertAdvertisementFailed {
            get {
                return ResourceManager.GetString("InsertAdvertisementFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới danh mục tin tức không thành công..
        /// </summary>
        public static string InsertContentCategoryFailed {
            get {
                return ResourceManager.GetString("InsertContentCategoryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới tin tức không thành công.
        /// </summary>
        public static string InsertContentFailed {
            get {
                return ResourceManager.GetString("InsertContentFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới nhóm danh mục tin tức không thành công.
        /// </summary>
        public static string InsertContentGroupFailed {
            get {
                return ResourceManager.GetString("InsertContentGroupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới nhãn cho tin tức không thành công.
        /// </summary>
        public static string InsertContentTagFailed {
            get {
                return ResourceManager.GetString("InsertContentTagFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới câu lạc bộ không thành công.
        /// </summary>
        public static string InsertFootballClubFailed {
            get {
                return ResourceManager.GetString("InsertFootballClubFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới cầu thủ không thành công.
        /// </summary>
        public static string InsertFootballerFailed {
            get {
                return ResourceManager.GetString("InsertFootballerFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới loại bàn thắng không thành công.
        /// </summary>
        public static string InsertGoalTypeFailed {
            get {
                return ResourceManager.GetString("InsertGoalTypeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới thông tin không thành công.
        /// </summary>
        public static string InsertInfoFailed {
            get {
                return ResourceManager.GetString("InsertInfoFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới trận đấu không không công.
        /// </summary>
        public static string InsertMatchFailed {
            get {
                return ResourceManager.GetString("InsertMatchFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới bàn thắng không không công.
        /// </summary>
        public static string InsertMatchGoalFailed {
            get {
                return ResourceManager.GetString("InsertMatchGoalFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới Menu không thành công.
        /// </summary>
        public static string InsertMenuFailed {
            get {
                return ResourceManager.GetString("InsertMenuFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới loại Menu không thành công.
        /// </summary>
        public static string InsertMenuTypeFailed {
            get {
                return ResourceManager.GetString("InsertMenuTypeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới điều lệ giải đấu  không thành công.
        /// </summary>
        public static string InsertRuleFailed {
            get {
                return ResourceManager.GetString("InsertRuleFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới CLB tham gia không thành công.
        /// </summary>
        public static string InsertSeasonClubFailed {
            get {
                return ResourceManager.GetString("InsertSeasonClubFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới mùa giải không thành công.
        /// </summary>
        public static string InsertSeasonFailed {
            get {
                return ResourceManager.GetString("InsertSeasonFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới vòng đấu mùa giải không thành công.
        /// </summary>
        public static string InsertSeasonRoundFailed {
            get {
                return ResourceManager.GetString("InsertSeasonRoundFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phân quyền không thành công.
        /// </summary>
        public static string InsertUserCredentialFailed {
            get {
                return ResourceManager.GetString("InsertUserCredentialFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới nhóm thành viên không thành công.
        /// </summary>
        public static string InsertUserGroupFailed {
            get {
                return ResourceManager.GetString("InsertUserGroupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới User không thành công.
        /// </summary>
        public static string InsertUserLogFailed {
            get {
                return ResourceManager.GetString("InsertUserLogFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới Role không thành công.
        /// </summary>
        public static string InsertUserRoleFailed {
            get {
                return ResourceManager.GetString("InsertUserRoleFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới thông tin thành công.
        /// </summary>
        public static string Pub_InsertSuccess {
            get {
                return ResourceManager.GetString("Pub_InsertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thông tin thành công.
        /// </summary>
        public static string Pub_UpdateSucess {
            get {
                return ResourceManager.GetString("Pub_UpdateSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bản ghi đã tồn tại.
        /// </summary>
        public static string RecordExist {
            get {
                return ResourceManager.GetString("RecordExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật vị trí quảng cáo không thành công.
        /// </summary>
        public static string UpdateAdsPostitionFailed {
            get {
                return ResourceManager.GetString("UpdateAdsPostitionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật quảng cáo không thành công.
        /// </summary>
        public static string UpdateAdvertisementFailed {
            get {
                return ResourceManager.GetString("UpdateAdvertisementFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật danh mục tin tức không thành công..
        /// </summary>
        public static string UpdateContentCategoryFailed {
            get {
                return ResourceManager.GetString("UpdateContentCategoryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật tin tức không thành công.
        /// </summary>
        public static string UpdateContentFailed {
            get {
                return ResourceManager.GetString("UpdateContentFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật nhóm danh mục tin tức không thành công.
        /// </summary>
        public static string UpdateContentGroupFailed {
            get {
                return ResourceManager.GetString("UpdateContentGroupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật nhãn cho tin tức không thành công.
        /// </summary>
        public static string UpdateContentTagFailed {
            get {
                return ResourceManager.GetString("UpdateContentTagFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật câu lạc bộ không thành công.
        /// </summary>
        public static string UpdateFootballClubFailed {
            get {
                return ResourceManager.GetString("UpdateFootballClubFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật cầu thủ không thành công.
        /// </summary>
        public static string UpdateFootballerFailed {
            get {
                return ResourceManager.GetString("UpdateFootballerFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật loại bàn thắng không thành công.
        /// </summary>
        public static string UpdateGoalTypeFailed {
            get {
                return ResourceManager.GetString("UpdateGoalTypeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thông tin không thành công.
        /// </summary>
        public static string UpdateInfoFailed {
            get {
                return ResourceManager.GetString("UpdateInfoFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật trận đấu không không công.
        /// </summary>
        public static string UpdateMatchFailed {
            get {
                return ResourceManager.GetString("UpdateMatchFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật bàn thắng không không công.
        /// </summary>
        public static string UpdateMatchGoalFailed {
            get {
                return ResourceManager.GetString("UpdateMatchGoalFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật Menu không thành công.
        /// </summary>
        public static string UpdateMenuFailed {
            get {
                return ResourceManager.GetString("UpdateMenuFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật loại Menu không thành công.
        /// </summary>
        public static string UpdateMenuTypeFailed {
            get {
                return ResourceManager.GetString("UpdateMenuTypeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật điều lệ giải đấu không thành công.
        /// </summary>
        public static string UpdateRuleFailed {
            get {
                return ResourceManager.GetString("UpdateRuleFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật CLB tham gia không thành công.
        /// </summary>
        public static string UpdateSeasonClubFailed {
            get {
                return ResourceManager.GetString("UpdateSeasonClubFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật mùa giải không thành công.
        /// </summary>
        public static string UpdateSeasonFailed {
            get {
                return ResourceManager.GetString("UpdateSeasonFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật vòng đấu mùa giải không thành công.
        /// </summary>
        public static string UpdateSeasonRoundFailed {
            get {
                return ResourceManager.GetString("UpdateSeasonRoundFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật phân quyền không thành công.
        /// </summary>
        public static string UpdateUserCredentialFailed {
            get {
                return ResourceManager.GetString("UpdateUserCredentialFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật nhóm người dùng không thành công.
        /// </summary>
        public static string UpdateUserGroupFailed {
            get {
                return ResourceManager.GetString("UpdateUserGroupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật User không không công.
        /// </summary>
        public static string UpdateUserLogFailed {
            get {
                return ResourceManager.GetString("UpdateUserLogFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật Role không thành công.
        /// </summary>
        public static string UpdateUserRoleFailed {
            get {
                return ResourceManager.GetString("UpdateUserRoleFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tài khoản đã tồn tại.
        /// </summary>
        public static string UsernameExists {
            get {
                return ResourceManager.GetString("UsernameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếng Việt.
        /// </summary>
        public static string Vietnamese {
            get {
                return ResourceManager.GetString("Vietnamese", resourceCulture);
            }
        }
    }
}
